CREATE TABLE IF NOT EXISTS speedtest (
    id INTEGER PRIMARY KEY,
    ping FLOAT NOT NULL,
    download FLOAT NOT NULL,
    upload FLOAT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);